### ISSUE TITLE
IPアドレスなしでOK？

### ISSUE THREAD

**Issue by suganoo** [mushahiroyuki/gowebprog#3]
https://github.com/mushahiroyuki/gowebprog/blob/master/ch07/14web_service/server.go#L29
すみません、少々気になったのですが、ここ "127.0.0.1:8080"っとIPなしでOKでしょうか？

動くと思いますが、ほかのファイルとの整合性でいいのかなと。

**Comment by mushahiroyuki** [comment]
「:8080」だけでもいいみたいです。まあ、ほかと揃えたほうがよいことはよいのでしょうが...

p. 22のリスト1.3や ch03/06handler/server.goなどでもあるようですので...。
