### ISSUE TITLE
User.Nameはどこから？

### ISSUE THREAD

**Issue by suganoo** [mushahiroyuki/gowebprog#4]
すみません低レベルの質問で恐縮なのですが、教えていただけませんでしょうか。

<質問>
index.htmlの `{{ .User.Name }}` はどこから渡しているのでしょうか？
https://github.com/mushahiroyuki/gowebprog/blob/46faa1da9ae329950ec5f94d903a3165646e9085/ch02/chitchat/templates/index.html#L12

Thread.UserIdとUser.Idを紐づけているとは思うのですが、Threads()を見返してみてもどこでjoinさせてるのかわからなかったもので。
https://github.com/mushahiroyuki/gowebprog/blob/46faa1da9ae329950ec5f94d903a3165646e9085/ch02/chitchat/data/thread.go#L92:L106

**Comment by mushahiroyuki** [comment]
すみません。しばらく触ってないので、思い出すのに時間がかかるかと思います。しばらくお待ちください。
--武舎広幸

**Comment by suganoo** [comment]
いえいえ全然かまいません。
わかりませんでもかまいませんし、xxxxxxのところ調べておいてくださいというヒントでも構いません。

**Comment by mushahiroyuki** [comment]
細かく読んでないのですが、p. 42のリスト2.9 あたりから後ろに説明があるように思えますが...

**Comment by suganoo** [comment]
うーん　読んでみたところ、明確にどう修正したらいいかよくわかりませんでした。
ともあれ、だいたいどうしたら良いかは想像つきましたので本件クローズします。

かなり間があったにもかかわらずお答えいただき、ありがとうございました。

**Comment by mushahiroyuki** [comment]
もう少し時間ができたら調べてみます。すみません。
