### ISSUE TITLE
P141 5.5 関数の部分で, テンプレートエンジンの組み込み関数の参照先

### ISSUE THREAD

**Issue by ysaito8015** [mushahiroyuki/gowebprog#6]
書籍 (2020年8月11日 初版第2刷) 記載内容 P141 L9
 (組み込み関数) "一覧については, パッケージ fmt のドキュメント参照"

おそらく, text/template もしくは html/template の誤りでしょうか
https://pkg.go.dev/text/template#hdr-Functions

**Comment by mushahiroyuki** [comment]
ご連絡ありがとうございます。
曖昧な表現でした。下記をご覧ください。
https://www.marlin-arms.com/support/goweb/errata.html

今後ともよろしくお願いいたします。
